### ISSUE TITLE
Comparing 0.0 and -0.0 during tests

### ISSUE THREAD

**Issue by gituser768** [mikera/core.matrix.complex#4]
While writing some tests for the PMatrixOps protocol, I've realized that 0.0 != -0.0 for Java doubles (see [this stackoverflow question](http://stackoverflow.com/questions/14771328/java-signed-zero-and-boxing)). Since complex numbers in Clojure ultimately just Java doubles, some tests that I've written which should pass, are reported as having failed.

``` Clojure
;; from complex.core
(defn complex-number
  "..."
  ([^double a] (Complex. a))
  ([^double a ^double b] (Complex. a b)))
```

To get around this, I just add 0.0 but it seems ugly. Can anyone suggest a better way to do this? Is there a comparison function I can use which will map -0.0 to 0.0?

Here is an example of -0.0 showing up where 0.0 makes more sense.

``` Clojure
(m/pm 
   (m/inverse 
      (cm/complex-array (m/identity-matrix 3))))
;;=>[[(1.0, -0.0) (0.0, -0.0) (0.0, -0.0)]
;;   [(0.0, -0.0) (1.0, -0.0) (0.0, -0.0)]
;;   [(0.0, -0.0) (0.0, -0.0) (1.0, -0.0)]]
```

Here is my part of test for the Hermitian Transpose function where I add 0.0 to each matrix element to coerce -0.0 to 0.0:

``` Clojure
(deftest herm-transpose
  (is (m/e= (m/add (cm/hermitian-transpose
                     (cm/complex-array (m/identity-matrix 2))) (c/complex-number 0 0))
            (cm/complex-array (m/identity-matrix 2))))
;;...
)
```

This test returns passes, but I wonder if there is a better (more straightforward) way to do this.

**Comment by mikera** [comment]
Should be possible to use the `c.c.m/equals` function with a tolerance?

**Comment by gituser768** [comment]
It looks like `c.c.m/equals` won't work for complex values:

> java.lang.ClassCastException: org.apache.commons.math3.complex.Complex cannot be cast to java.lang.Number

Which is to be expected since we haven't told it how to use the `epsilon` input to compare the complex numbers. Unless you mean that I should implement the protocol for c.c.mp/equals for complex values. That seems like the most logical way to me.

**Comment by gituser768** [comment]
Done, though I'm not sure if there is a more efficient way:

``` Clojure
mp/PMatrixEqualityEpsilon
  (matrix-equals-epsilon
     [a b eps]
    (every?
      identity
      (mapv (fn [alpha beta]
                (Complex/equals ^Complex alpha ^Complex beta ^double eps))
            (m/eseq a)
            (m/eseq b))))
```

**Comment by mikera** [comment]
Looks like a reasonably sane approach. Can probably be made faster (there's a lot of boxing / unboxing going on there....) but that can be left for future optimisation. I've merged your PR.
